server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
